### PR TITLE
Authentication screens

### PR DESCRIPTION
**Pull request by Lokeshkhati**
image

image

Screens for authentication

### CODE REVIEW

**Review by Priyanshi-Tiwari — APPROVED** [review]
Everything looks good to me. Good job @Lokeshkhati

**Review by Sameony — APPROVED** [review]
Very nice and clean code. You can merge it.

**Review by krishanu2911 — APPROVED** [review]
No changes required 
Well written code!!

**Review by vaibhav-mahalle — APPROVED** [review]
good job. nice and clean code. looks good to me.

**Pull request merged**
